### ISSUE TITLE
Missing podman::rootless_users parameter

### ISSUE THREAD

**Issue by silug** [southalc/podman#38]
Regarding the discussion on https://github.com/southalc/podman/pull/34 and the changes in 707adf4cd2e1d12806562db1232ad02723468efd, the `podman::rootless_users` parameter was added in https://github.com/southalc/podman/pull/19 in order to support configuration of rootless users (and their corresponding API socket) via hiera.

Please revert that change.  (Also, the solution in #34 appears to be correct.)

**Comment by silug** [comment]
FYI, I use this to manage gitlab-runner.  (The docker executor talks to the API socket.)

The full config looks something like this:

```yaml
---
classes:
  - gitlab_ci_runner
  - accounts
  - podman
  - systemd

gitlab_ci_runner::runner_defaults:
  url: '*** INSERT GITLAB URL HERE ***'
  registration-token: >
    ENC[*** INSERT EYAML-ENCODED GITLAB REGISTRATION TOKEN HERE ***]
  executor: docker

gitlab_ci_runner::runners:
  "%{facts.hostname}-docker":
    tag-list: docker

accounts::user_list:
  gitlab-runner:
    comment: 'GitLab Runner'
    system: true
    home: /home/gitlab-runner
    group: gitlab-runner
    groups:
      - gitlab-runner

accounts::group_list:
  gitlab-runner:
    system: true

podman::manage_subuid: true
podman::subid:
  gitlab-runner:
    subuid: 100000
    count: 65535
podman::rootless_users:
  - gitlab-runner
podman::enable_api_socket: true

systemd::dropin_files:
  podman.conf:
    unit: gitlab-runner.service
    content: |
      [Service]
      Environment="DOCKER_HOST=unix://%{facts.podman.socket.gitlab-runner}"
    notify_service: true
```
